compute:
  batch_size: 128
  epochs: 90
  print_freq: 10
  resume: null
  seed: null
  start_epoch: 0
  use_cuda: true
  workers: 8
dataset:
  class_names:
  - completely_round_smooth
  - in_between_smooth
  - cigar_shaped_smooth
  - edge_on
  - spiral
  clf_images_dir: clf_images
  clf_labels_file: clf_labels.csv
  clf_labels_split_file: clf_labels_split.csv
  dir: dataset
  eda_table: eda_table
  eda_table_split: eda_table_split
  name: galaxy-zoo
  predictions_file: predictions.csv
  reg_images_test_dir: images_test_rev1
  reg_images_train_dir: images_training_rev1
  reg_labels_file: training_solutions_rev1.csv
  test_split_ratio: 0.1
  val_split_ratio: 0.1
  version: latest
debug: false
distributed:
  dist_backend: nccl
  dist_url: tcp://224.66.41.62:23456
  gpu: null
  multiprocessing_distributed: false
  ngpus_per_node: 1
  rank: -1
  use: false
  world_size: -1
exp:
  evaluate: false
  name: null
  task: classification
  test: false
model:
  arch: resnet18
  freeze: false
  output_constraints: true
  path: null
  pretrained: false
optimizer:
  lr: 0.0003
  lr_scheduler_freq: 30
  momentum: 0.9
  name: adam
  weight_decay: 0.0001
preprocess:
  augmentation: true
  color_jitter: true
  color_jitter_factor: 0.1
  flip: true
  rotate: true
wandb:
  entity: aliberts
  freq: 10
  note: null
  project: galaxy-zoo
  run_name: null
  tags:
  - baseline
  - model exploration
  use: false
